### ISSUE TITLE
make sure copyright and licensing info are included in images

### ISSUE THREAD

**Issue by cjdcordeiro** [ubuntu-rocks/dotnet#28]
when chiseling a new ROCK, make sure the corresponding packages copyrights are also included in the final image.

Same goes for cases where the software is being installed from an external source, like a tarbal.

References:
 - https://www.debian.org/doc/debian-policy/ch-docs.html#s-copyrightfile
 - MSFT's source pedigree guidelines: https://github.com/dotnet/dotnet-docker/blob/main/documentation/image-artifact-details.md

**Comment by woky** [comment]
Each deb's copyright file contains license text so common-licenses from base files is not needed. Implemented in chisel: https://github.com/canonical/chisel/pull/18
