### ISSUE TITLE
[QUESTION] Chiseled Images for .Net Isolated Functions

### ISSUE THREAD

**Issue by tomasopye** [ubuntu-rocks/dotnet#319]
Is there any plan to produce chiseled versions of the dotnet isolated function images (found here: https://hub.docker.com/_/microsoft-azure-functions-dotnet-isolated)? 

If so when do you expect those to be available in preview?

If not, why?

**Comment by cjdcordeiro** [comment]
Hi @tomasopye !

We currently have no plans for releasing those additional function images. The reasons are:
 1. Chisel relies solely on the Ubuntu archives, which means a debian package must exist in order for it to be chiselled.
 2. These chiselled images are meant to be used as "bases" for user builds. Thus, whenever additional software is required (like an additional package slice or application binaries) we recommend that users add those, as described in https://github.com/ubuntu-rocks/dotnet#building-the-net-application-image

I hope that helps

**Comment by tomasopye** [comment]
thank you for the response, and yes it does help.
