### ISSUE TITLE
Provide way to get OS information from container

### ISSUE THREAD

**Issue by mthalman** [ubuntu-rocks/dotnet#80]
**Is your feature request related to a problem? Please describe.**

It can be helpful to determine the origin of the image's content (provenance) in a way that the container's file system describes. 

**Describe the solution you'd like**

I should be able to look for the /etc/os-release file in the container's file system to get the OS version information. This functionality is embedded in [Syft](https://github.com/anchore/syft), for example.

This is the current behavior:

```shell
> syft packages --output json -q ubuntu/dotnet-runtime:6.0-22.04_edge | jq -r .distro
{}
```

This is the output I would like to see instead:

```json
{
  "prettyName": "Ubuntu 22.04.1 LTS",
  "name": "Ubuntu",
  "id": "ubuntu",
  "idLike": [
    "debian"
  ],
  "version": "22.04.1 LTS (Jammy Jellyfish)",
  "versionID": "22.04",
  "versionCodename": "jammy",
  "homeURL": "https://www.ubuntu.com/",
  "supportURL": "https://help.ubuntu.com/",
  "bugReportURL": "https://bugs.launchpad.net/ubuntu/",
  "privacyPolicyURL": "https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
}
```

This is the same output that you would see when targeting the full Ubuntu image tag:

```shell
syft packages --output json -q ubuntu:22.04 | jq -r .distro
```

**Comment by cjdcordeiro** [comment]
Hi @mthalman 

y this is doable. We just need this PR (https://github.com/canonical/chisel-releases/pull/14/files) to be merged

**Comment by cjdcordeiro** [comment]
Let me know if the content proposed in (https://github.com/canonical/chisel-releases/pull/14/files) fits your request ;)

**Comment by mthalman** [comment]
> Let me know if the content proposed in (https://github.com/canonical/chisel-releases/pull/14/files) fits your request ;)

Yes, it looks like it should.
